apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-strip-prefix@kubernetescrd
spec:
  rules:
    - host: pabq.pausescape.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami-service
                port:
                  number: 80
          - path: /userservice
            pathType: Prefix
            backend:
              service:
                name: userservice
                port:
                  number: 80
          - path: /pointservice
            pathType: Prefix
            backend:
              service:
                name: pointservice-svc
                port:
                  number: 80
          - path: /rankingservice
            pathType: Prefix
            backend:
              service:
                name: rankingservice-svc
                port:
                  number: 80